import type { editor } from "monaco-editor";

export const CYBERPUNK_THEME_ID = "cyberpunk-dark";

export const cyberpunkTheme: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "e0e0f0", background: "0a0a0f" },
    { token: "comment", foreground: "30305a", fontStyle: "italic" },
    { token: "keyword", foreground: "ff00aa", fontStyle: "bold" },
    { token: "keyword.control", foreground: "ff00aa" },
    { token: "keyword.operator", foreground: "00f0ff" },
    { token: "string", foreground: "00ff88" },
    { token: "string.escape", foreground: "ffaa00" },
    { token: "number", foreground: "ffaa00" },
    { token: "type", foreground: "00f0ff" },
    { token: "type.identifier", foreground: "00f0ff" },
    { token: "class", foreground: "00f0ff", fontStyle: "bold" },
    { token: "function", foreground: "e0e0f0" },
    { token: "variable", foreground: "e0e0f0" },
    { token: "variable.parameter", foreground: "ffaa00" },
    { token: "constant", foreground: "ffaa00" },
    { token: "operator", foreground: "00f0ff" },
    { token: "delimiter", foreground: "6060a0" },
    { token: "delimiter.bracket", foreground: "6060a0" },
    { token: "tag", foreground: "ff00aa" },
    { token: "attribute.name", foreground: "00f0ff" },
    { token: "attribute.value", foreground: "00ff88" },
    { token: "regexp", foreground: "ff00aa" },
    { token: "invalid", foreground: "ff0000", fontStyle: "underline" },
  ],
  colors: {
    "editor.background": "#0a0a0f",
    "editor.foreground": "#e0e0f0",
    "editor.lineHighlightBackground": "#0f0f1a",
    "editor.lineHighlightBorder": "#1a1a2e",
    "editor.selectionBackground": "#00f0ff30",
    "editor.selectionHighlightBackground": "#00f0ff15",
    "editor.wordHighlightBackground": "#ff00aa20",
    "editor.wordHighlightStrongBackground": "#ff00aa40",
    "editor.findMatchBackground": "#ffaa0040",
    "editor.findMatchHighlightBackground": "#ffaa0020",
    "editorCursor.foreground": "#00f0ff",
    "editorWhitespace.foreground": "#1a1a2e",
    "editorIndentGuide.background": "#1a1a2e",
    "editorIndentGuide.activeBackground": "#6060a0",
    "editorLineNumber.foreground": "#30305a",
    "editorLineNumber.activeForeground": "#6060a0",
    "editorGutter.background": "#0a0a0f",
    "editorGutter.addedBackground": "#00ff8880",
    "editorGutter.modifiedBackground": "#ffaa0080",
    "editorGutter.deletedBackground": "#ff00aa80",
    "editorRuler.foreground": "#1a1a2e",
    "editorBracketMatch.background": "#00f0ff20",
    "editorBracketMatch.border": "#00f0ff",
    "editorOverviewRuler.border": "#0a0a0f",
    "editorError.foreground": "#ff0044",
    "editorWarning.foreground": "#ffaa00",
    "scrollbar.shadow": "#00000080",
    "scrollbarSlider.background": "#6060a030",
    "scrollbarSlider.hoverBackground": "#6060a060",
    "scrollbarSlider.activeBackground": "#00f0ff40",
    "minimap.background": "#0a0a0f",
    "minimap.selectionHighlight": "#00f0ff40",
    "panel.background": "#0a0a0f",
    "panel.border": "#1a1a2e",
    "statusBar.background": "#0f0f1a",
    "statusBar.foreground": "#6060a0",
    "statusBarItem.hoverBackground": "#1a1a2e",
    "tab.activeBackground": "#0f0f1a",
    "tab.inactiveBackground": "#0a0a0f",
    "tab.activeForeground": "#00f0ff",
    "tab.inactiveForeground": "#30305a",
    "tab.border": "#1a1a2e",
    "tab.activeBorder": "#00f0ff",
  },
};
